# src/pyquifer/__init__.py

"""
PyQuifer: A PyTorch library for simulating consciousness through generative world models.

This package provides tools for building "Physical Intelligence" models that
"resonate" with data rather than merely calculating answers, bridging
Physical Intelligence with Cognitive Architecture.

OPTIMIZED: Lazy loading of all modules - import time reduced from 2300ms to <50ms.
Components are loaded on first access, not at import time.
"""

__version__ = "0.1.0"

# Library-level logging: attach NullHandler so users aren't forced into our config.
# Users call logging.basicConfig() or configure handlers in their own code.
import logging

logging.getLogger(__name__).addHandler(logging.NullHandler())

# Define what can be imported - actual loading happens lazily
__all__ = [
    "PyQuifer",
    "PerturbationLayer",
    "LearnableKuramotoBank",
    "Snake",
    "MultiAttractorPotential",
    "MindEyeActualization",
    "GenerativeWorldModel",
    "FrequencyBank",
    "HarmonicOscillator",
    "LinOSSLayer",
    "LinOSSEncoder",
    "LIFNeuron",
    "SpikingLayer",
    "OscillatorySNN",
    "STDPLayer",
    "surrogate_spike",
    "NoveltyDetector",
    "MasterySignal",
    "CoherenceReward",
    "IntrinsicMotivationSystem",
    "EpistemicValue",
    # Multiplexing
    "PhaseGate",
    "CrossFrequencyCoupling",
    "TemporalMultiplexer",
    "PhaseEncoder",
    "NestedOscillator",
    # Consciousness
    "PerturbationalComplexity",
    "IntegrationMeasure",
    "DifferentiationMeasure",
    "ConsciousnessMonitor",
    # Criticality
    "AvalancheDetector",
    "BranchingRatio",
    "CriticalityController",
    "HomeostaticRegulator",
    "KuramotoCriticalityMonitor",
    # Learning
    "EligibilityTrace",
    "RewardModulatedHebbian",
    "ContrastiveHebbian",
    "PredictiveCoding",
    # Spherical Kuramoto (from akorn)
    "SphericalKuramotoLayer",
    "SphericalKuramotoBank",
    "LearnableOmega",
    "TangentProjection",
    "normalize_oscillators",
    "exponential_map",
    # Active Inference (from Deep_AIF/pymdp)
    "ActiveInferenceAgent",
    "ExpectedFreeEnergy",
    "PredictiveEncoder",
    "PredictiveDecoder",
    "TransitionModel",
    "BeliefUpdate",
    "reparameterize",
    "kl_divergence_gaussian",
    # Thermodynamic (from generative_thermodynamic_computing/Neuroca)
    "ThermodynamicOscillatorSystem",
    "SimulatedAnnealing",
    "LangevinDynamics",
    "TemperatureSchedule",
    "PhaseTransitionDetector",
    # IIT Metrics (from pyphi)
    "EarthMoverDistance",
    "KLDivergence",
    "L1Distance",
    "InformationDensity",
    "PartitionedInformation",
    "IntegratedInformation",
    "CauseEffectRepertoire",
    "IITConsciousnessMonitor",
    "hamming_distance_matrix",
    "generate_bipartitions",
    "Concept",
    "SystemIrreducibilityAnalysis",
    # Hyperdimensional Computing (HDC/HRR)
    "circular_convolution",
    "circular_correlation",
    "normalize_hd",
    "HypervectorMemory",
    "PhaseBinder",
    "ResonantBinding",
    "HDCReasoner",
    # Neuromodulation (three-timescale dynamics)
    "NeuromodulatorState",
    "NeuromodulatorDynamics",
    "GlialLayer",
    "StochasticResonance",
    "InjectionLocking",
    "ThreeTimescaleNetwork",
    # Liquid Networks (LTC, Neural ODEs)
    "LiquidTimeConstantCell",
    "NeuralODE",
    "ODEFunc",
    "ContinuousTimeRNN",
    "MetastableCell",
    # Reservoir Computing (ESN)
    "EchoStateNetwork",
    "IntrinsicPlasticity",
    "ReservoirWithIP",
    "CriticalReservoir",
    "spectral_radius",
    "scale_spectral_radius",
    # Phase Attention (Kuramoto-based transformers)
    "PhaseAttention",
    "PhaseMultiHeadAttention",
    "HybridPhaseAttention",
    "OscillatorGatedFFN",
    # Hypernetworks (dynamic weight generation)
    "HyperNetwork",
    "OscillatorHyperNetwork",
    "DynamicLinear",
    "ContextualReservoir",
    # Advanced Spiking (2nd order LIF, E/I balance, reward modulation)
    "SynapticNeuron",
    "AlphaNeuron",
    "RecurrentSynapticLayer",
    "RewardPredictionError",
    "EligibilityModulatedSTDP",
    # Kindchenschema Safety Interface (neoteny-inspired safety)
    "SafetyEnvelope",
    "ParentModule",
    "ReflexToStrategy",
    "LimbicResonance",
    # Morphological Computation (embodied cognition)
    "TensionField",
    "PeripheralGanglion",
    "SleepWakeController",
    "MorphologicalMemory",
    "DistributedBody",
    # Social Cognition (mirror neurons, ethics as thermodynamics)
    "MirrorResonance",
    "SocialCoupling",
    "EmpatheticConstraint",
    "ConstitutionalResonance",
    "OscillatoryEconomy",
    "TheoryOfMind",
    # Developmental Cognition (cute as dynamics, not pixels)
    "DynamicalSignatureDetector",
    "KindchenschemaDetector",
    "ProtectiveDrive",
    "EvolutionaryAttractor",
    "IntrinsicCuteUnderstanding",
    "DevelopmentalStageDetector",
    "PotentialActualization",
    # Ecological Cognition (digital species)
    "TimeScale",
    "ChronobiologicalSystem",
    "ImmunologicalLayer",
    "SynapticHomeostasis",
    "Umwelt",
    "AgencyMaintenance",
    "EcologicalSystem",
    # Somatic Layer (hardware → feelings)
    "SomaticState",
    "HardwareSensor",
    "SomaticManifold",
    "SomaticIntegrator",
    # Metacognitive Loop (thinking about thinking)
    "ConfidenceLevel",
    "ReasoningStep",
    "MetacognitiveState",
    "ConfidenceEstimator",
    "ReasoningMonitor",
    "MetacognitiveLoop",
    # Hyperbolic Geometry (curved thought space)
    "HyperbolicOperations",
    "HyperbolicLinear",
    "EmotionalGravityManifold",
    "MixedCurvatureManifold",
    # Strange Attractors (fractal personality)
    "LorenzAttractor",
    "PersonalityAttractor",
    "FractalSelfModel",
    "AttractorState",
    # X-16/X-17: Enhanced fractal personality and learning
    "MultiScaleFractalPersonality",
    "FractalPatternLearner",
    "create_enhanced_fractal_self",
    # Continual Learning (anti-forgetting)
    "ElasticWeightConsolidation",
    "SynapticIntelligence",
    "ContinualBackprop",
    "MESU",
    "ExperienceReplay",
    "ContinualLearner",
    # Quantum Cognition (superposition decisions)
    "QuantumState",
    "UnitaryTransform",
    "ProjectiveMeasurement",
    "QuantumInterference",
    "QuantumEntanglement",
    "QuantumDecisionMaker",
    "QuantumMemory",
    # World Models (imagination and planning)
    "WorldModelState",
    "RSSM",
    "NeuralODEDynamics",
    "WorldModel",
    "ImaginationBasedPlanner",
    # Global Workspace (consciousness bottleneck)
    "SalienceComputer",
    "IgnitionDynamics",
    "CompetitionDynamics",
    "PrecisionWeighting",
    "GlobalBroadcast",
    "GlobalWorkspace",
    "HierarchicalWorkspace",
    # Voice Dynamics (oscillator → prosody)
    "SpeechRhythm",
    "VoiceEffects",
    "SpeechOscillator",
    "VoiceNeuromodulation",
    "ProsodyModulator",
    "VoiceDynamicsSystem",
    # Precision Weighting (attention as gain control)
    "PrecisionEstimator",
    "PrecisionGate",
    "AttentionAsPrecision",
    # Hierarchical Predictive Coding (multi-level generative model)
    "PredictiveLevel",
    "HierarchicalPredictiveCoding",
    # Metastability (winnerless competition, heteroclinic channels)
    "WinnerlessCompetition",
    "HeteroclinicChannel",
    "MetastabilityIndex",
    # Adaptive Stochastic Resonance (optimal noise finding)
    "AdaptiveStochasticResonance",
    "ResonanceMonitor",
    # Causal Flow (transfer entropy, directed information)
    "TransferEntropyEstimator",
    "CausalFlowMap",
    "DominanceDetector",
    # Memory Consolidation (sleep replay, episodic→semantic)
    "EpisodicBuffer",
    "SharpWaveRipple",
    "ConsolidationEngine",
    "MemoryReconsolidation",
    # Self-Model (minimal phenomenal self, Markov blanket)
    "MarkovBlanket",
    "SelfModel",
    "NarrativeIdentity",
    # Neural Darwinism (neuronal group selection)
    "NeuronalGroup",
    "SelectionArena",
    "SymbiogenesisDetector",
    # Integration (cognitive cycle)
    "CycleConfig",
    "CognitiveCycle",
    "TickResult",
    "PROCESSING_MODE_PERCEPTION",
    "PROCESSING_MODE_IMAGINATION",
    "PROCESSING_MODE_BALANCED",
    "PROCESSING_MODE_NAMES",
    # Bridge (LLM modulation API)
    "PyQuiferBridge",
    "ModulationState",
    "sync_debug_mode",
    "SteppedModulator",
    "PyQuiferLogitsProcessor",
    # Volatility Filter (adaptive learning rates from HGF)
    "VolatilityNode",
    "HierarchicalVolatilityFilter",
    "VolatilityGatedLearning",
    # Phase 5: OU Noise (stochastic resonance)
    "OrnsteinUhlenbeckNoise",
    # Phase 5: Short-Term Plasticity (Tsodyks-Markram)
    "TsodyksMarkramSynapse",
    "STPLayer",
    # Phase 5: Kuramoto-Daido Mean-Field
    "KuramotoDaidoMeanField",
    # Phase 5: Stuart-Landau Oscillator
    "StuartLandauOscillator",
    # Sensory-Oscillator Coupling
    "SensoryCoupling",
    # Phase 5: E-prop Dual Eligibility
    "EpropSTDP",
    # Phase 5: Differentiable Plasticity + Learnable Eligibility
    "DifferentiablePlasticity",
    "LearnableEligibilityTrace",
    # Phase 5: Speciated Neural Darwinism
    "SpeciatedSelectionArena",
    # Phase 5: AdEx Neuron
    "AdExNeuron",
    # Phase 5: Koopman Bifurcation Detection
    "KoopmanBifurcationDetector",
    # Phase 5: Wilson-Cowan Neural Mass
    "WilsonCowanPopulation",
    "WilsonCowanNetwork",
    # Phase 6: New spiking primitives
    "SpikeEncoder",
    "SpikeDecoder",
    "SynapticDelay",
    # Phase 7: Benchmark gap-closure
    "PhaseTopologyCache",
    "NoProgressDetector",
    "EvidenceSource",
    "EvidenceAggregator",
    "HypothesisProfile",
    # Phase 8: Training core
    "EquilibriumPropagationTrainer",
    "EPKuramotoClassifier",
    "OscillationGatedPlasticity",
    "ThreeFactorRule",
    "OscillatoryPredictiveCoding",
    "SleepReplayConsolidation",
    "DendriticNeuron",
    "DendriticStack",
    # Phase 9: Organ protocol + GWT wiring
    "Organ",
    "Proposal",
    "OscillatoryWriteGate",
    "PreGWAdapter",
    "HPCOrgan",
    "MotivationOrgan",
    "SelectionOrgan",
    "DiversityTracker",
    # Phase 9b: MCP-as-Organ protocol
    "MCPOrgan",
    "MCPOrganConfig",
    # Phase 10: Multi-workspace ensemble + cross-bleed
    "StandingBroadcast",
    "CrossBleedGate",
    "WorkspaceEnsemble",
    # Phase 11: ODE Solvers
    "SolverConfig",
    "EulerSolver",
    "RK4Solver",
    "DopriSolver",
    "solve_ivp",
    "create_solver",
    # Phase 11: Complex Oscillators
    "ComplexKuramotoBank",
    "ComplexCoupling",
    "ModReLU",
    "ComplexLinear",
    "ComplexBatchNorm",
    "complex_order_parameter",
    # Phase 11: CUDA Kernels
    "KuramotoCUDAKernel",
    "TensorDiagnostics",
    # Phase 12: Visual Binding (AKOrN)
    "AKOrNLayer",
    "AKOrNBlock",
    "AKOrNEncoder",
    "OscillatorySegmenter",
    "BindingReadout",
    # Phase 12: Temporal Binding
    "SequenceAKOrN",
    "PhaseGrouping",
    "OscillatoryChunking",
    # Phase 12: Sensory Binding
    "MultimodalBinder",
    "BindingStrength",
    "CrossModalAttention",
    "ModalityEncoder",
    # Phase 13: Deep Active Inference
    "DeepAIF",
    "LatentTransitionModel",
    "PolicyNetwork",
    "MultiStepPlanner",
    # Phase 13: JEPA
    "JEPAEncoder",
    "JEPAPredictor",
    "VICRegLoss",
    "BarlowLoss",
    "ActionJEPA",
    # Phase 13: Deliberation
    "Deliberator",
    "ProcessRewardModel",
    "BeamSearchReasoner",
    "SelfCorrectionLoop",
    "ComputeBudget",
    # Phase 14: CLS Memory
    "HippocampalModule",
    "NeocorticalModule",
    "ConsolidationScheduler",
    "ForgettingCurve",
    "ImportanceScorer",
    "MemoryInterference",
    # Phase 14: Temporal Knowledge Graph
    "TemporalNode",
    "TemporalEdge",
    "TemporalKnowledgeGraph",
    "EventTimeline",
    "TemporalReasoner",
    # Phase 14: Gated Memory
    "NMDAGate",
    "DifferentiableMemoryBank",
    "MemoryConsolidationLoop",
    # Phase 15: Cognitive Appraisal
    "AppraisalDimension",
    "AppraisalChain",
    "OCCModel",
    "OCC_Model",  # backward compat alias
    "EmotionAttribution",
    # Phase 15: Causal Reasoning
    "CausalGraph",
    "DoOperator",
    "CounterfactualEngine",
    "CausalDiscovery",
    "InterventionalQuery",
    # Phase 16: Selective SSM
    "SelectiveStateSpace",
    "SelectiveScan",
    "SSMBlock",
    "MambaLayer",
    "OscillatorySSM",
    # Phase 16: Oscillatory MoE
    "ExpertPool",
    "OscillatorRouter",
    "SparseMoE",
    # Phase 16: Graph Reasoning
    "DynamicGraphAttention",
    "MessagePassingWithPhase",
    "TemporalGraphTransformer",
    # Phase 17: Prospective Configuration
    "ProspectiveInference",
    "ProspectiveHebbian",
    "InferThenModify",
    # Phase 17: Dendritic Learning
    "PyramidalNeuron",
    "DendriticLocalizedLearning",
    "DendriticErrorSignal",
    # Phase 17: Energy Spiking PC
    "EnergyOptimizedSNN",
    "MultiCompartmentSpikingPC",
    "EnergyLandscape",
    # Phase 18: FHRR
    "FHRREncoder",
    "LatencyEncoder",
    "SpikeVSAOps",
    "NeuromorphicExporter",
    # Phase 18: FlashRNN
    "FlashLTC",
    "FlashCfC",
    "FlashLTCLayer",
    # Adapter Manager (oscillator-driven LoRA)
    "AdapterManager",
    "AdapterGate",
    "AdapterConfig",
    "BlendState",
    # Basal Ganglia Gating Loop
    "BasalGangliaLoop",
    "GatingOutput",
    # Phase-Lock Bus (multimodal coordinator)
    "PhaseLockBus",
    "BusConfig",
    "BusOutput",
    # Neuroscience Diagnostics (Tier 1 empirical metrics)
    "spectral_exponent",
    "dfa_exponent",
    "lempel_ziv_complexity",
    "avalanche_statistics",
    "complexity_entropy",
]

# Mapping from name to (module, attribute) for lazy loading
# Paths point directly to canonical locations (not through shims)
_LAZY_IMPORTS = {
    "PyQuifer": (".api.legacy", "PyQuifer"),
    "PerturbationLayer": (".memory.perturbation", "PerturbationLayer"),
    "LearnableKuramotoBank": (".dynamics.oscillators.kuramoto", "LearnableKuramotoBank"),
    "Snake": (".dynamics.oscillators.kuramoto", "Snake"),
    "FrequencyBank": (".dynamics.oscillators.frequency_bank", "FrequencyBank"),
    "MultiAttractorPotential": (".memory.potentials", "MultiAttractorPotential"),
    "MindEyeActualization": (".memory.diffusion", "MindEyeActualization"),
    "GenerativeWorldModel": (".memory.generative_world_model", "GenerativeWorldModel"),
    "HarmonicOscillator": (".dynamics.continuous.linoss", "HarmonicOscillator"),
    "LinOSSLayer": (".dynamics.continuous.linoss", "LinOSSLayer"),
    "LinOSSEncoder": (".dynamics.continuous.linoss", "LinOSSEncoder"),
    "LIFNeuron": (".dynamics.spiking.neurons", "LIFNeuron"),
    "SpikingLayer": (".dynamics.spiking.neurons", "SpikingLayer"),
    "OscillatorySNN": (".dynamics.spiking.neurons", "OscillatorySNN"),
    "STDPLayer": (".dynamics.spiking.neurons", "STDPLayer"),
    "surrogate_spike": (".dynamics.spiking.neurons", "surrogate_spike"),
    "NoveltyDetector": (".cognition.control.motivation", "NoveltyDetector"),
    "MasterySignal": (".cognition.control.motivation", "MasterySignal"),
    "CoherenceReward": (".cognition.control.motivation", "CoherenceReward"),
    "IntrinsicMotivationSystem": (".cognition.control.motivation", "IntrinsicMotivationSystem"),
    "EpistemicValue": (".cognition.control.motivation", "EpistemicValue"),
    "PhaseGate": (".dynamics.oscillators.coupling", "PhaseGate"),
    "CrossFrequencyCoupling": (".dynamics.oscillators.coupling", "CrossFrequencyCoupling"),
    "TemporalMultiplexer": (".dynamics.oscillators.coupling", "TemporalMultiplexer"),
    "PhaseEncoder": (".dynamics.oscillators.coupling", "PhaseEncoder"),
    "NestedOscillator": (".dynamics.oscillators.coupling", "NestedOscillator"),
    "PerturbationalComplexity": (".identity.consciousness", "PerturbationalComplexity"),
    "IntegrationMeasure": (".identity.consciousness", "IntegrationMeasure"),
    "DifferentiationMeasure": (".identity.consciousness", "DifferentiationMeasure"),
    "ConsciousnessMonitor": (".identity.consciousness", "ConsciousnessMonitor"),
    "AvalancheDetector": (".dynamics.criticality.monitors", "AvalancheDetector"),
    "BranchingRatio": (".dynamics.criticality.monitors", "BranchingRatio"),
    "CriticalityController": (".dynamics.criticality.controllers", "CriticalityController"),
    "HomeostaticRegulator": (".dynamics.criticality.controllers", "HomeostaticRegulator"),
    "KuramotoCriticalityMonitor": (".dynamics.criticality.monitors", "KuramotoCriticalityMonitor"),
    "EligibilityTrace": (".learning.synaptic", "EligibilityTrace"),
    "RewardModulatedHebbian": (".learning.synaptic", "RewardModulatedHebbian"),
    "ContrastiveHebbian": (".learning.synaptic", "ContrastiveHebbian"),
    "PredictiveCoding": (".learning.synaptic", "PredictiveCoding"),
    "SphericalKuramotoLayer": (".dynamics.oscillators.spherical", "SphericalKuramotoLayer"),
    "SphericalKuramotoBank": (".dynamics.oscillators.spherical", "SphericalKuramotoBank"),
    "LearnableOmega": (".dynamics.oscillators.spherical", "LearnableOmega"),
    "TangentProjection": (".dynamics.oscillators.spherical", "TangentProjection"),
    "normalize_oscillators": (".dynamics.oscillators.spherical", "normalize_oscillators"),
    "exponential_map": (".dynamics.oscillators.spherical", "exponential_map"),
    "ActiveInferenceAgent": (".cognition.predictive.active_inference", "ActiveInferenceAgent"),
    "ExpectedFreeEnergy": (".cognition.predictive.active_inference", "ExpectedFreeEnergy"),
    "PredictiveEncoder": (".cognition.predictive.active_inference", "PredictiveEncoder"),
    "PredictiveDecoder": (".cognition.predictive.active_inference", "PredictiveDecoder"),
    "TransitionModel": (".cognition.predictive.active_inference", "TransitionModel"),
    "BeliefUpdate": (".cognition.predictive.active_inference", "BeliefUpdate"),
    "reparameterize": (".cognition.predictive.active_inference", "reparameterize"),
    "kl_divergence_gaussian": (".cognition.predictive.active_inference", "kl_divergence_gaussian"),
    "ThermodynamicOscillatorSystem": (".dynamics.continuous.thermodynamic", "ThermodynamicOscillatorSystem"),
    "SimulatedAnnealing": (".dynamics.continuous.thermodynamic", "SimulatedAnnealing"),
    "LangevinDynamics": (".dynamics.continuous.thermodynamic", "LangevinDynamics"),
    "TemperatureSchedule": (".dynamics.continuous.thermodynamic", "TemperatureSchedule"),
    "PhaseTransitionDetector": (".dynamics.continuous.thermodynamic", "PhaseTransitionDetector"),
    "EarthMoverDistance": (".identity.iit_metrics", "EarthMoverDistance"),
    "KLDivergence": (".identity.iit_metrics", "KLDivergence"),
    "L1Distance": (".identity.iit_metrics", "L1Distance"),
    "InformationDensity": (".identity.iit_metrics", "InformationDensity"),
    "PartitionedInformation": (".identity.iit_metrics", "PartitionedInformation"),
    "IntegratedInformation": (".identity.iit_metrics", "IntegratedInformation"),
    "CauseEffectRepertoire": (".identity.iit_metrics", "CauseEffectRepertoire"),
    "IITConsciousnessMonitor": (".identity.iit_metrics", "IITConsciousnessMonitor"),
    "hamming_distance_matrix": (".identity.iit_metrics", "hamming_distance_matrix"),
    "generate_bipartitions": (".identity.iit_metrics", "generate_bipartitions"),
    "Concept": (".identity.iit_metrics", "Concept"),
    "SystemIrreducibilityAnalysis": (".identity.iit_metrics", "SystemIrreducibilityAnalysis"),
    "circular_convolution": (".experimental.hyperdimensional", "circular_convolution"),
    "circular_correlation": (".experimental.hyperdimensional", "circular_correlation"),
    "normalize_hd": (".experimental.hyperdimensional", "normalize_hd"),
    "HypervectorMemory": (".experimental.hyperdimensional", "HypervectorMemory"),
    "PhaseBinder": (".experimental.hyperdimensional", "PhaseBinder"),
    "ResonantBinding": (".experimental.hyperdimensional", "ResonantBinding"),
    "HDCReasoner": (".experimental.hyperdimensional", "HDCReasoner"),
    "NeuromodulatorState": (".dynamics.neuromodulation", "NeuromodulatorState"),
    "NeuromodulatorDynamics": (".dynamics.neuromodulation", "NeuromodulatorDynamics"),
    "GlialLayer": (".dynamics.neuromodulation", "GlialLayer"),
    "StochasticResonance": (".dynamics.neuromodulation", "StochasticResonance"),
    "InjectionLocking": (".dynamics.neuromodulation", "InjectionLocking"),
    "ThreeTimescaleNetwork": (".dynamics.neuromodulation", "ThreeTimescaleNetwork"),
    "LiquidTimeConstantCell": (".dynamics.continuous.liquid", "LiquidTimeConstantCell"),
    "NeuralODE": (".dynamics.continuous.liquid", "NeuralODE"),
    "ODEFunc": (".dynamics.continuous.liquid", "ODEFunc"),
    "ContinuousTimeRNN": (".dynamics.continuous.liquid", "ContinuousTimeRNN"),
    "MetastableCell": (".dynamics.continuous.liquid", "MetastableCell"),
    "EchoStateNetwork": (".experimental.reservoir", "EchoStateNetwork"),
    "IntrinsicPlasticity": (".experimental.reservoir", "IntrinsicPlasticity"),
    "ReservoirWithIP": (".experimental.reservoir", "ReservoirWithIP"),
    "CriticalReservoir": (".experimental.reservoir", "CriticalReservoir"),
    "spectral_radius": (".experimental.reservoir", "spectral_radius"),
    "scale_spectral_radius": (".experimental.reservoir", "scale_spectral_radius"),
    "PhaseAttention": (".cognition.attention.phase_attention", "PhaseAttention"),
    "PhaseMultiHeadAttention": (".cognition.attention.phase_attention", "PhaseMultiHeadAttention"),
    "HybridPhaseAttention": (".cognition.attention.phase_attention", "HybridPhaseAttention"),
    "OscillatorGatedFFN": (".cognition.attention.phase_attention", "OscillatorGatedFFN"),
    "HyperNetwork": (".identity.hypernetwork", "HyperNetwork"),
    "OscillatorHyperNetwork": (".identity.hypernetwork", "OscillatorHyperNetwork"),
    "DynamicLinear": (".identity.hypernetwork", "DynamicLinear"),
    "ContextualReservoir": (".identity.hypernetwork", "ContextualReservoir"),
    "SynapticNeuron": (".dynamics.spiking.advanced", "SynapticNeuron"),
    "AlphaNeuron": (".dynamics.spiking.advanced", "AlphaNeuron"),
    "RecurrentSynapticLayer": (".dynamics.spiking.advanced", "RecurrentSynapticLayer"),
    "RewardPredictionError": (".dynamics.spiking.advanced", "RewardPredictionError"),
    "EligibilityModulatedSTDP": (".dynamics.spiking.advanced", "EligibilityModulatedSTDP"),
    "SafetyEnvelope": (".embodiment.safety", "SafetyEnvelope"),
    "ParentModule": (".embodiment.safety", "ParentModule"),
    "ReflexToStrategy": (".embodiment.safety", "ReflexToStrategy"),
    "LimbicResonance": (".embodiment.safety", "LimbicResonance"),
    "TensionField": (".embodiment.morphology", "TensionField"),
    "PeripheralGanglion": (".embodiment.morphology", "PeripheralGanglion"),
    "SleepWakeController": (".embodiment.morphology", "SleepWakeController"),
    "MorphologicalMemory": (".embodiment.morphology", "MorphologicalMemory"),
    "DistributedBody": (".embodiment.morphology", "DistributedBody"),
    "MirrorResonance": (".embodiment.social", "MirrorResonance"),
    "SocialCoupling": (".embodiment.social", "SocialCoupling"),
    "EmpatheticConstraint": (".embodiment.social", "EmpatheticConstraint"),
    "ConstitutionalResonance": (".embodiment.social", "ConstitutionalResonance"),
    "OscillatoryEconomy": (".embodiment.social", "OscillatoryEconomy"),
    "TheoryOfMind": (".embodiment.social", "TheoryOfMind"),
    "DynamicalSignatureDetector": (".embodiment.developmental", "DynamicalSignatureDetector"),
    "KindchenschemaDetector": (".embodiment.developmental", "KindchenschemaDetector"),
    "ProtectiveDrive": (".embodiment.developmental", "ProtectiveDrive"),
    "EvolutionaryAttractor": (".embodiment.developmental", "EvolutionaryAttractor"),
    "IntrinsicCuteUnderstanding": (".embodiment.developmental", "IntrinsicCuteUnderstanding"),
    "DevelopmentalStageDetector": (".embodiment.developmental", "DevelopmentalStageDetector"),
    "PotentialActualization": (".embodiment.developmental", "PotentialActualization"),
    "TimeScale": (".embodiment.ecology", "TimeScale"),
    "ChronobiologicalSystem": (".embodiment.ecology", "ChronobiologicalSystem"),
    "ImmunologicalLayer": (".embodiment.ecology", "ImmunologicalLayer"),
    "SynapticHomeostasis": (".embodiment.ecology", "SynapticHomeostasis"),
    "Umwelt": (".embodiment.ecology", "Umwelt"),
    "AgencyMaintenance": (".embodiment.ecology", "AgencyMaintenance"),
    "EcologicalSystem": (".embodiment.ecology", "EcologicalSystem"),
    "SomaticState": (".embodiment.somatic", "SomaticState"),
    "HardwareSensor": (".embodiment.somatic", "HardwareSensor"),
    "SomaticManifold": (".embodiment.somatic", "SomaticManifold"),
    "SomaticIntegrator": (".embodiment.somatic", "SomaticIntegrator"),
    "ConfidenceLevel": (".cognition.control.metacognitive", "ConfidenceLevel"),
    "ReasoningStep": (".cognition.control.metacognitive", "ReasoningStep"),
    "MetacognitiveState": (".cognition.control.metacognitive", "MetacognitiveState"),
    "ConfidenceEstimator": (".cognition.control.metacognitive", "ConfidenceEstimator"),
    "ReasoningMonitor": (".cognition.control.metacognitive", "ReasoningMonitor"),
    "MetacognitiveLoop": (".cognition.control.metacognitive", "MetacognitiveLoop"),
    "HyperbolicOperations": (".experimental.hyperbolic", "HyperbolicOperations"),
    "HyperbolicLinear": (".experimental.hyperbolic", "HyperbolicLinear"),
    "EmotionalGravityManifold": (".experimental.hyperbolic", "EmotionalGravityManifold"),
    "MixedCurvatureManifold": (".experimental.hyperbolic", "MixedCurvatureManifold"),
    "LorenzAttractor": (".identity.strange_attractor", "LorenzAttractor"),
    "PersonalityAttractor": (".identity.strange_attractor", "PersonalityAttractor"),
    "FractalSelfModel": (".identity.strange_attractor", "FractalSelfModel"),
    "AttractorState": (".identity.strange_attractor", "AttractorState"),
    "MultiScaleFractalPersonality": (".identity.strange_attractor", "MultiScaleFractalPersonality"),
    "FractalPatternLearner": (".identity.strange_attractor", "FractalPatternLearner"),
    "create_enhanced_fractal_self": (".identity.strange_attractor", "create_enhanced_fractal_self"),
    "ElasticWeightConsolidation": (".learning.continual", "ElasticWeightConsolidation"),
    "SynapticIntelligence": (".learning.continual", "SynapticIntelligence"),
    "ContinualBackprop": (".learning.continual", "ContinualBackprop"),
    "MESU": (".learning.continual", "MESU"),
    "ExperienceReplay": (".learning.continual", "ExperienceReplay"),
    "ContinualLearner": (".learning.continual", "ContinualLearner"),
    "QuantumState": (".experimental.quantum", "QuantumState"),
    "UnitaryTransform": (".experimental.quantum", "UnitaryTransform"),
    "ProjectiveMeasurement": (".experimental.quantum", "ProjectiveMeasurement"),
    "QuantumInterference": (".experimental.quantum", "QuantumInterference"),
    "QuantumEntanglement": (".experimental.quantum", "QuantumEntanglement"),
    "QuantumDecisionMaker": (".experimental.quantum", "QuantumDecisionMaker"),
    "QuantumMemory": (".experimental.quantum", "QuantumMemory"),
    "WorldModelState": (".memory.latent_world_model", "WorldModelState"),
    "RSSM": (".memory.latent_world_model", "RSSM"),
    "NeuralODEDynamics": (".memory.latent_world_model", "NeuralODEDynamics"),
    "WorldModel": (".memory.latent_world_model", "WorldModel"),
    "ImaginationBasedPlanner": (".memory.latent_world_model", "ImaginationBasedPlanner"),
    "SalienceComputer": (".workspace.competition", "SalienceComputer"),
    "IgnitionDynamics": (".workspace.competition", "IgnitionDynamics"),
    "CompetitionDynamics": (".workspace.competition", "CompetitionDynamics"),
    "PrecisionWeighting": (".workspace.competition", "PrecisionWeighting"),
    "GlobalBroadcast": (".workspace.broadcast", "GlobalBroadcast"),
    "GlobalWorkspace": (".workspace.workspace", "GlobalWorkspace"),
    "HierarchicalWorkspace": (".workspace.ensemble", "HierarchicalWorkspace"),
    "SpeechRhythm": (".embodiment.voice", "SpeechRhythm"),
    "VoiceEffects": (".embodiment.voice", "VoiceEffects"),
    "SpeechOscillator": (".embodiment.voice", "SpeechOscillator"),
    "VoiceNeuromodulation": (".embodiment.voice", "VoiceNeuromodulation"),
    "ProsodyModulator": (".embodiment.voice", "ProsodyModulator"),
    "VoiceDynamicsSystem": (".embodiment.voice", "VoiceDynamicsSystem"),
    "PrecisionEstimator": (".cognition.attention.precision_weighting", "PrecisionEstimator"),
    "PrecisionGate": (".cognition.attention.precision_weighting", "PrecisionGate"),
    "AttentionAsPrecision": (".cognition.attention.precision_weighting", "AttentionAsPrecision"),
    "PredictiveLevel": (".cognition.predictive.hierarchical", "PredictiveLevel"),
    "HierarchicalPredictiveCoding": (".cognition.predictive.hierarchical", "HierarchicalPredictiveCoding"),
    "WinnerlessCompetition": (".dynamics.metastability", "WinnerlessCompetition"),
    "HeteroclinicChannel": (".dynamics.metastability", "HeteroclinicChannel"),
    "MetastabilityIndex": (".dynamics.metastability", "MetastabilityIndex"),
    "AdaptiveStochasticResonance": (".dynamics.stochastic", "AdaptiveStochasticResonance"),
    "ResonanceMonitor": (".dynamics.stochastic", "ResonanceMonitor"),
    "TransferEntropyEstimator": (".cognition.reasoning.causal_flow", "TransferEntropyEstimator"),
    "CausalFlowMap": (".cognition.reasoning.causal_flow", "CausalFlowMap"),
    "DominanceDetector": (".cognition.reasoning.causal_flow", "DominanceDetector"),
    "EpisodicBuffer": (".learning.consolidation", "EpisodicBuffer"),
    "SharpWaveRipple": (".learning.consolidation", "SharpWaveRipple"),
    "ConsolidationEngine": (".learning.consolidation", "ConsolidationEngine"),
    "MemoryReconsolidation": (".learning.consolidation", "MemoryReconsolidation"),
    "MarkovBlanket": (".identity.self_model", "MarkovBlanket"),
    "SelfModel": (".identity.self_model", "SelfModel"),
    "NarrativeIdentity": (".identity.self_model", "NarrativeIdentity"),
    "NeuronalGroup": (".identity.neural_darwinism", "NeuronalGroup"),
    "SelectionArena": (".identity.neural_darwinism", "SelectionArena"),
    "SymbiogenesisDetector": (".identity.neural_darwinism", "SymbiogenesisDetector"),
    "CycleConfig": (".runtime.config", "CycleConfig"),
    "CognitiveCycle": (".runtime.cycle", "CognitiveCycle"),
    "TickResult": (".runtime.tick_result", "TickResult"),
    "PROCESSING_MODE_PERCEPTION": (".runtime.tick_result", "PROCESSING_MODE_PERCEPTION"),
    "PROCESSING_MODE_IMAGINATION": (".runtime.tick_result", "PROCESSING_MODE_IMAGINATION"),
    "PROCESSING_MODE_BALANCED": (".runtime.tick_result", "PROCESSING_MODE_BALANCED"),
    "PROCESSING_MODE_NAMES": (".runtime.tick_result", "PROCESSING_MODE_NAMES"),
    "PyQuiferBridge": (".api.bridge", "PyQuiferBridge"),
    "sync_debug_mode": (".api.bridge", "sync_debug_mode"),
    "SteppedModulator": (".api.bridge", "SteppedModulator"),
    "PyQuiferLogitsProcessor": (".api.bridge", "PyQuiferLogitsProcessor"),
    "ModulationState": (".api.bridge", "ModulationState"),
    "VolatilityNode": (".cognition.control.volatility", "VolatilityNode"),
    "HierarchicalVolatilityFilter": (".cognition.control.volatility", "HierarchicalVolatilityFilter"),
    "VolatilityGatedLearning": (".cognition.control.volatility", "VolatilityGatedLearning"),
    "OrnsteinUhlenbeckNoise": (".dynamics.stochastic", "OrnsteinUhlenbeckNoise"),
    "TsodyksMarkramSynapse": (".learning.stp", "TsodyksMarkramSynapse"),
    "STPLayer": (".learning.stp", "STPLayer"),
    "KuramotoDaidoMeanField": (".dynamics.oscillators.mean_field", "KuramotoDaidoMeanField"),
    "StuartLandauOscillator": (".dynamics.oscillators.stuart_landau", "StuartLandauOscillator"),
    "SensoryCoupling": (".dynamics.oscillators.kuramoto", "SensoryCoupling"),
    "EpropSTDP": (".dynamics.spiking.advanced", "EpropSTDP"),
    "DifferentiablePlasticity": (".learning.synaptic", "DifferentiablePlasticity"),
    "LearnableEligibilityTrace": (".learning.synaptic", "LearnableEligibilityTrace"),
    "SpeciatedSelectionArena": (".identity.neural_darwinism", "SpeciatedSelectionArena"),
    "AdExNeuron": (".dynamics.spiking.neurons", "AdExNeuron"),
    "KoopmanBifurcationDetector": (".dynamics.criticality.monitors", "KoopmanBifurcationDetector"),
    "WilsonCowanPopulation": (".dynamics.continuous.neural_mass", "WilsonCowanPopulation"),
    "WilsonCowanNetwork": (".dynamics.continuous.neural_mass", "WilsonCowanNetwork"),
    "SpikeEncoder": (".dynamics.spiking.neurons", "SpikeEncoder"),
    "SpikeDecoder": (".dynamics.spiking.neurons", "SpikeDecoder"),
    "SynapticDelay": (".dynamics.spiking.neurons", "SynapticDelay"),
    "PhaseTopologyCache": (".dynamics.oscillators.mean_field", "PhaseTopologyCache"),
    "NoProgressDetector": (".dynamics.criticality.controllers", "NoProgressDetector"),
    "EvidenceSource": (".cognition.control.metacognitive", "EvidenceSource"),
    "EvidenceAggregator": (".cognition.control.metacognitive", "EvidenceAggregator"),
    "HypothesisProfile": (".identity.neural_darwinism", "HypothesisProfile"),
    "EquilibriumPropagationTrainer": (".learning.equilibrium_prop", "EquilibriumPropagationTrainer"),
    "EPKuramotoClassifier": (".learning.equilibrium_prop", "EPKuramotoClassifier"),
    "OscillationGatedPlasticity": (".learning.synaptic", "OscillationGatedPlasticity"),
    "ThreeFactorRule": (".learning.synaptic", "ThreeFactorRule"),
    "OscillatoryPredictiveCoding": (".cognition.predictive.hierarchical", "OscillatoryPredictiveCoding"),
    "SleepReplayConsolidation": (".learning.consolidation", "SleepReplayConsolidation"),
    "DendriticNeuron": (".learning.dendritic", "DendriticNeuron"),
    "DendriticStack": (".learning.dendritic", "DendriticStack"),
    "Organ": (".workspace.organ_base", "Organ"),
    "Proposal": (".workspace.organ_base", "Proposal"),
    "OscillatoryWriteGate": (".workspace.organ_base", "OscillatoryWriteGate"),
    "PreGWAdapter": (".workspace.organ_base", "PreGWAdapter"),
    "HPCOrgan": (".workspace.organ_base", "HPCOrgan"),
    "MotivationOrgan": (".workspace.organ_base", "MotivationOrgan"),
    "SelectionOrgan": (".workspace.organ_base", "SelectionOrgan"),
    "DiversityTracker": (".workspace.ensemble", "DiversityTracker"),
    "MCPOrgan": (".workspace.organ_mcp", "MCPOrgan"),
    "MCPOrganConfig": (".workspace.organ_mcp", "MCPOrganConfig"),
    "StandingBroadcast": (".workspace.broadcast", "StandingBroadcast"),
    "CrossBleedGate": (".workspace.ensemble", "CrossBleedGate"),
    "WorkspaceEnsemble": (".workspace.ensemble", "WorkspaceEnsemble"),
    "SolverConfig": (".dynamics.continuous.ode_solvers", "SolverConfig"),
    "EulerSolver": (".dynamics.continuous.ode_solvers", "EulerSolver"),
    "RK4Solver": (".dynamics.continuous.ode_solvers", "RK4Solver"),
    "DopriSolver": (".dynamics.continuous.ode_solvers", "DopriSolver"),
    "solve_ivp": (".dynamics.continuous.ode_solvers", "solve_ivp"),
    "create_solver": (".dynamics.continuous.ode_solvers", "create_solver"),
    "ComplexKuramotoBank": (".dynamics.oscillators.complex", "ComplexKuramotoBank"),
    "ComplexCoupling": (".dynamics.oscillators.complex", "ComplexCoupling"),
    "ModReLU": (".dynamics.oscillators.complex", "ModReLU"),
    "ComplexLinear": (".dynamics.oscillators.complex", "ComplexLinear"),
    "ComplexBatchNorm": (".dynamics.oscillators.complex", "ComplexBatchNorm"),
    "complex_order_parameter": (".dynamics.oscillators.complex", "complex_order_parameter"),
    "KuramotoCUDAKernel": (".accel.cuda.kuramoto_kernel", "KuramotoCUDAKernel"),
    "TensorDiagnostics": (".accel.cuda.kuramoto_kernel", "TensorDiagnostics"),
    "AKOrNLayer": (".cognition.binding.visual", "AKOrNLayer"),
    "AKOrNBlock": (".cognition.binding.visual", "AKOrNBlock"),
    "AKOrNEncoder": (".cognition.binding.visual", "AKOrNEncoder"),
    "OscillatorySegmenter": (".cognition.binding.visual", "OscillatorySegmenter"),
    "BindingReadout": (".cognition.binding.visual", "BindingReadout"),
    "SequenceAKOrN": (".cognition.binding.temporal", "SequenceAKOrN"),
    "PhaseGrouping": (".cognition.binding.temporal", "PhaseGrouping"),
    "OscillatoryChunking": (".cognition.binding.temporal", "OscillatoryChunking"),
    "MultimodalBinder": (".cognition.binding.sensory", "MultimodalBinder"),
    "BindingStrength": (".cognition.binding.sensory", "BindingStrength"),
    "CrossModalAttention": (".cognition.binding.sensory", "CrossModalAttention"),
    "ModalityEncoder": (".cognition.binding.sensory", "ModalityEncoder"),
    "DeepAIF": (".cognition.predictive.deep_active_inference", "DeepAIF"),
    "LatentTransitionModel": (".cognition.predictive.deep_active_inference", "LatentTransitionModel"),
    "PolicyNetwork": (".cognition.predictive.deep_active_inference", "PolicyNetwork"),
    "MultiStepPlanner": (".cognition.predictive.deep_active_inference", "MultiStepPlanner"),
    "JEPAEncoder": (".cognition.predictive.jepa", "JEPAEncoder"),
    "JEPAPredictor": (".cognition.predictive.jepa", "JEPAPredictor"),
    "VICRegLoss": (".cognition.predictive.jepa", "VICRegLoss"),
    "BarlowLoss": (".cognition.predictive.jepa", "BarlowLoss"),
    "ActionJEPA": (".cognition.predictive.jepa", "ActionJEPA"),
    "Deliberator": (".cognition.control.deliberation", "Deliberator"),
    "ProcessRewardModel": (".cognition.control.deliberation", "ProcessRewardModel"),
    "BeamSearchReasoner": (".cognition.control.deliberation", "BeamSearchReasoner"),
    "SelfCorrectionLoop": (".cognition.control.deliberation", "SelfCorrectionLoop"),
    "ComputeBudget": (".cognition.control.deliberation", "ComputeBudget"),
    "HippocampalModule": (".memory.cls", "HippocampalModule"),
    "NeocorticalModule": (".memory.cls", "NeocorticalModule"),
    "ConsolidationScheduler": (".memory.cls", "ConsolidationScheduler"),
    "ForgettingCurve": (".memory.cls", "ForgettingCurve"),
    "ImportanceScorer": (".memory.cls", "ImportanceScorer"),
    "MemoryInterference": (".memory.cls", "MemoryInterference"),
    "TemporalNode": (".cognition.reasoning.temporal_graph", "TemporalNode"),
    "TemporalEdge": (".cognition.reasoning.temporal_graph", "TemporalEdge"),
    "TemporalKnowledgeGraph": (".cognition.reasoning.temporal_graph", "TemporalKnowledgeGraph"),
    "EventTimeline": (".cognition.reasoning.temporal_graph", "EventTimeline"),
    "TemporalReasoner": (".cognition.reasoning.temporal_graph", "TemporalReasoner"),
    "NMDAGate": (".memory.gated_memory", "NMDAGate"),
    "DifferentiableMemoryBank": (".memory.gated_memory", "DifferentiableMemoryBank"),
    "MemoryConsolidationLoop": (".memory.gated_memory", "MemoryConsolidationLoop"),
    "AppraisalDimension": (".cognition.control.appraisal", "AppraisalDimension"),
    "AppraisalChain": (".cognition.control.appraisal", "AppraisalChain"),
    "OCCModel": (".cognition.control.appraisal", "OCCModel"),
    "OCC_Model": (".cognition.control.appraisal", "OCC_Model"),
    "EmotionAttribution": (".cognition.control.appraisal", "EmotionAttribution"),
    "CausalGraph": (".cognition.reasoning.causal_reasoning", "CausalGraph"),
    "DoOperator": (".cognition.reasoning.causal_reasoning", "DoOperator"),
    "CounterfactualEngine": (".cognition.reasoning.causal_reasoning", "CounterfactualEngine"),
    "CausalDiscovery": (".cognition.reasoning.causal_reasoning", "CausalDiscovery"),
    "InterventionalQuery": (".cognition.reasoning.causal_reasoning", "InterventionalQuery"),
    "SelectiveStateSpace": (".cognition.routing.ssm", "SelectiveStateSpace"),
    "SelectiveScan": (".cognition.routing.ssm", "SelectiveScan"),
    "SSMBlock": (".cognition.routing.ssm", "SSMBlock"),
    "MambaLayer": (".cognition.routing.ssm", "MambaLayer"),
    "OscillatorySSM": (".cognition.routing.ssm", "OscillatorySSM"),
    "ExpertPool": (".cognition.routing.moe", "ExpertPool"),
    "OscillatorRouter": (".cognition.routing.moe", "OscillatorRouter"),
    "SparseMoE": (".cognition.routing.moe", "SparseMoE"),
    "DynamicGraphAttention": (".cognition.reasoning.graph_reasoning", "DynamicGraphAttention"),
    "MessagePassingWithPhase": (".cognition.reasoning.graph_reasoning", "MessagePassingWithPhase"),
    "TemporalGraphTransformer": (".cognition.reasoning.graph_reasoning", "TemporalGraphTransformer"),
    "ProspectiveInference": (".learning.prospective", "ProspectiveInference"),
    "ProspectiveHebbian": (".learning.prospective", "ProspectiveHebbian"),
    "InferThenModify": (".learning.prospective", "InferThenModify"),
    "PyramidalNeuron": (".learning.dendritic_learning", "PyramidalNeuron"),
    "DendriticLocalizedLearning": (".learning.dendritic_learning", "DendriticLocalizedLearning"),
    "DendriticErrorSignal": (".learning.dendritic_learning", "DendriticErrorSignal"),
    "EnergyOptimizedSNN": (".dynamics.spiking.energy", "EnergyOptimizedSNN"),
    "MultiCompartmentSpikingPC": (".dynamics.spiking.energy", "MultiCompartmentSpikingPC"),
    "EnergyLandscape": (".dynamics.spiking.energy", "EnergyLandscape"),
    "FHRREncoder": (".experimental.fhrr", "FHRREncoder"),
    "LatencyEncoder": (".experimental.fhrr", "LatencyEncoder"),
    "SpikeVSAOps": (".experimental.fhrr", "SpikeVSAOps"),
    "NeuromorphicExporter": (".experimental.fhrr", "NeuromorphicExporter"),
    "FlashLTC": (".cognition.routing.flash_rnn", "FlashLTC"),
    "FlashCfC": (".cognition.routing.flash_rnn", "FlashCfC"),
    "FlashLTCLayer": (".cognition.routing.flash_rnn", "FlashLTCLayer"),
    "AdapterManager": (".identity.adapter_manager", "AdapterManager"),
    "AdapterGate": (".identity.adapter_manager", "AdapterGate"),
    "AdapterConfig": (".identity.adapter_manager", "AdapterConfig"),
    "BlendState": (".identity.adapter_manager", "BlendState"),
    "BasalGangliaLoop": (".dynamics.basal_ganglia", "BasalGangliaLoop"),
    "GatingOutput": (".dynamics.basal_ganglia", "GatingOutput"),
    "PhaseLockBus": (".dynamics.phase_lock_bus", "PhaseLockBus"),
    "BusConfig": (".dynamics.phase_lock_bus", "BusConfig"),
    "BusOutput": (".dynamics.phase_lock_bus", "BusOutput"),
    "spectral_exponent": (".diagnostics.neuroscience", "spectral_exponent"),
    "dfa_exponent": (".diagnostics.neuroscience", "dfa_exponent"),
    "lempel_ziv_complexity": (".diagnostics.neuroscience", "lempel_ziv_complexity"),
    "avalanche_statistics": (".diagnostics.neuroscience", "avalanche_statistics"),
    "complexity_entropy": (".diagnostics.neuroscience", "complexity_entropy"),
}

# Cache for loaded attributes
_loaded = {}


def __getattr__(name: str):
    """Lazy load attributes on first access."""
    if name in _loaded:
        return _loaded[name]

    if name in _LAZY_IMPORTS:
        module_path, attr_name = _LAZY_IMPORTS[name]
        # Import the module
        import importlib
        module = importlib.import_module(module_path, package=__name__)
        # Get the attribute
        attr = getattr(module, attr_name)
        # Cache it
        _loaded[name] = attr
        return attr

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    """List available names for autocomplete."""
    return __all__
